---
name: Build, Push, and Deploy

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  SSH_HOST: ${{ secrets.SSH_HOST }}
  SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
  ENABLE_SSL: ${{ secrets.ENABLE_SSL }}

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub 
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - name: Build Docker Image
        run: docker build -t "$IMAGE_NAME:latest" .

      - name: Push Docker image 
        run: docker push "$IMAGE_NAME:latest"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > private.key
          chmod 600 private.key
          eval "$(ssh-agent -s)"
          ssh-add private.key
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          ssh-keyscan "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Setup Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible 

      - name: Create Ansible inventory
        run: |
          echo "Server ansible_host=$SSH_HOST ansible_user=$SSH_USERNAME ansible_ssh_private_key_file=private.key" > inventory

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i inventory \
            --extra-vars "image_name=$IMAGE_NAME" \
            --extra-vars "domain_name=$DOMAIN_NAME" \
            --extra-vars "dockerhub_username=$DOCKERHUB_USERNAME" \
            --extra-vars "dockerhub_token=$DOCKERHUB_TOKEN" \
            --extra-vars "enable_ssl=$ENABLE_SSL" \
            devops/playbook.yml
#error on docker tocken